### ISSUE TITLE
Question about methodology used for evaluating FlashConv against cuFFT

### ISSUE THREAD

**Issue by sylee0124** [HazyResearch/H3#23]
Hi, I have a question related to a Figure in the H3 paper.
In Figure 2, it shows performance evaluation of FlashConv against cuFFT and attention.
Is it correct to think that it's comparing all operations in H3, including qkv computation and kernel generations and not just FFTconv related operation (FFTconv + elementwise multiplication + residual computation)?
![image](https://user-images.githubusercontent.com/47180088/228109528-f1e2c488-6ef2-4030-847e-7e71c6c2f25f.png)

**Comment by tridao** [comment]
Here we're just considering the FFTConv related operations (fft, pointwise multiplication, inverse fft).

**Comment by sylee0124** [comment]
Thanks for the reply!👍
